### ISSUE TITLE
If there is no link preview, the link is not visible at all

### ISSUE THREAD

**Issue by kenodressel** [aeternity/superhero-ui#248]
For example:
![image](https://user-images.githubusercontent.com/765921/77749886-1b281780-7023-11ea-9cbb-bd7c621bf3b7.png)

The link should be displayed, even if there is no preview.

**Comment by mradkov** [comment]
This was fixed here: https://github.com/aeternity/aepp-raendom/pull/203

apparently someone did overwrite it..

**Comment by venimus** [comment]
I just had formatted it https://github.com/aeternity/aepp-raendom/pull/232/files#diff-0c9c134dbd57fccd61d57dc7ad9fac6fR120-R126

Imho it looks like this case wasn't covered

**Comment by venimus** [comment]
I think the problem is that there was no `http://` in the url when submitted by the user. The parser couldn't access it, then failed to generate any preview out of it. I think the backend should prepend the missing prefixes before trying to access the site, also frontend should prefix the href with //

**Comment by mradkov** [comment]
There always should be `http/https` prefix on the URL sent for tipping.

**Comment by venimus** [comment]
Yes, it appears the validation failed for some reason probably due to a bug and there is now invalid data in the db.
