### ISSUE TITLE
Not supported browser

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#297]
Display warning when user opens superhero from a browser which we don't support (do not have extension available for). E.g. safari, IE.

**Comment by venimus** [comment]
I really think we have to add few of the chrome-based browsers that can install the extension to "supported" also Opera, Vivaldi are already mentioned in Help sections

**Comment by venimus** [comment]
I reopen the issue, because there will be some changes in the Wizard that mention other browsers (TBD), and will be awkward to show Unsupported on top, while the wizard explains the opposite. So we can update the list later. 
Also I'm also concerned about this feature in general, as it is not really clear what "Unsupported" means. Site works on most browsers, but the extension does not. Yet using the site just for looking around does not require you to have an extension. Furthermore we have that backup web wallet, which does not require extension and people still can use the site's full functionality.
 So IMHO this message should be somehow in the context of wallet support/installation, not the aggregator in general.
