### ISSUE TITLE
fallback if backend is erroring

### ISSUE THREAD

**Issue by mradkov** [aeternity/superhero-ui#379]
We have problems with CORS appearing sometimes and this is causing the UI to hang on spinning loader.

We can still fetch the tips if there is other error, also if the backend is not responding we can fetch them from the contract.

**Comment by CedrikNikita** [comment]
From my point of view this problem can be solved in two ways:
* Fast one is to add a new method that will have additional url not only to a backend and will try to get info from there if backend has issues. Like
backendSafeFetch(mainUrl, fallbackUrl)
* Best solution would be (it was also mentioned by @davidyuk ) fix all CORS related issues, and not overload the code with workarounds and hack-like decisions. Because that will slow working of aggregator and will also slow adding a new features.
