### ISSUE TITLE
Crash when trying to upload picture 

### ISSUE THREAD

**Issue by bissembert1618** [aeternity/superhero-ui#714]
**Describe the bug**
When I try to upload a picture for my profile, the website crashes. 

**To Reproduce**
1. Go to profile
2. Click on the upload button
3. See the error 

**Desktop (please complete the following information):**
 - OS: IPadOS 13
 - Browser: Safari 
 - Version: latest
![IMG_0040](https://user-images.githubusercontent.com/34056189/87637818-781f1900-c74b-11ea-8c07-2c9b2b4f634f.png)

**Comment by shapkarin** [comment]
I think it's because `backendError` event was emitted and next listened:
https://github.com/aeternity/superhero-ui/blob/d3c10028d478411092658924ae2d79e6fa65df23/src/App.vue#L51-L55
But not sure what the error. 

I also see the same maintance page when I turned on uBlock block extension at Chrome and open the main page. @bissembert1618 do you have some ad blocking extension? If you do, try to turn it off and reproduce.

**Comment by bissembert1618** [comment]
I have 3rd party adblocker. On safari tho you have a native one if I am not wrong. Will try again using a different browser and will revert.

**Comment by shapkarin** [comment]
I'm not sure the reason why it blocked by ad blocker, but maybe it will be nice to avoid that somehow.

**Comment by shapkarin** [comment]
Not sure that yours issue is related to the advertisement blocking.
But that’s totally because “backendError” was emitted, because that boy one
place in whole project where that is event listen and page forwarded to the
maintenance one. Not sure why it was emitted in yours case.

**Comment by shapkarin** [comment]
> I think it's because `backendError` event was emitted and next listened:
> https://github.com/aeternity/superhero-ui/blob/d3c10028d478411092658924ae2d79e6fa65df23/src/App.vue#L51-L55
> 
> 
> But not sure what the error.
> I also see the same maintance page when I turned on uBlock block extension at Chrome and open the main page. @bissembert1618 do you have some ad blocking extension? If you do, try to turn it off and reproduce.

@bissembert1618 Not sure that yours issue is related to the advertisement blocking.
But that’s totally because `backendError` was emitted – because that is only one
place in the whole project where that event is listen and next on that event page is forwards to the
maintenance one. Not sure why it was emitted in yours case. Let's find out, maybe it's some API calls blocking or something different.

**Comment by bissembert1618** [comment]
Thanks for this.

**Comment by shapkarin** [comment]
@bissembert1618 I tried to open my profile page without uBlock in Chrome from PC, then switch on the uBlock and also saw `maintenance` page. But uBlock also blocks almost any request to superhero backend. 
Maybe some Safari blocking work different, like not blocking all. So maybe that bug related to the API calls blocking, not sure. The better way to check is use dev tools and watch the requests and logs, can you try that?

**Comment by shapkarin** [comment]
> The better way to check is use dev tools and watch the requests and logs, can you try that?

@bissembert1618 I'm about approach to check that all in the same environment that you mentioned at the issue. Here is apple docs – https://developer.apple.com/safari/tools

**Comment by shapkarin** [comment]
@bissembert1618 and send the network and console tabs output

**Comment by bissembert1618** [comment]
Will try but I used an IPad.
Will find a solution to extract the logs. I need to connect my iPad to my Mac. Will revert soon.

**Comment by mradkov** [comment]
I think the issue is the nginx config for file uploads. The current limit is very low I guess.

**Comment by mradkov** [comment]
@bissembert1618 is this issue resolved? Can you still reproduce it?

**Comment by bissembert1618** [comment]
All is ok now. Thanks for this.
