### ISSUE TITLE
Wrong preview on the SH ui

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/superhero-ui#868]
Incorrect display of previews on superhero ui:
![Знімок екрана 2020-10-29 о 7 42 27 пп](https://user-images.githubusercontent.com/69896204/97611496-eea40600-1a1e-11eb-920f-447e4af3a349.png)

 - OS:  iOS 10.15.7
 - Browser: chrome

**Comment by mradkov** [comment]
This is actually already fixed in the staging where the new previews are already implemented, and will be available with the next release:

<img width="640" alt="Screenshot 2020-10-29 at 20 43 36" src="https://user-images.githubusercontent.com/13139371/97618222-7261f080-1a27-11eb-9248-9698dddb63c1.png">
